apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    {{- include "observability.labels" (dict "root" . "component" "grafana") | nindent 4 }}
data:
  datasources.yml: |
{{ .Values.grafana.datasources | nindent 4 }}
