apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    {{- include "observability.labels" (dict "root" . "component" "otel-collector") | nindent 4 }}
data:
  otel-collector-config.yaml: |
{{ .Values.otelCollector.config | nindent 4 }}
