apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    {{- include "observability.labels" (dict "root" . "component" "prometheus") | nindent 4 }}
data:
  prometheus.yml: |
{{ .Values.prometheus.config | nindent 4 }}
