apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  labels:
    {{- include "observability.labels" (dict "root" . "component" "tempo") | nindent 4 }}
data:
  tempo.yaml: |
{{ .Values.tempo.config | nindent 4 }}
