services:
  orders:
    build: ../services/orders
    ports:
      - "8001:8000"
    volumes:
      - ../services/orders:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - ecommerce-net
    depends_on:
      kafka:
        condition: service_healthy

  inventory:
    build: ../services/inventory
    ports:
      - "8002:8000"
    volumes:
      - ../services/inventory:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - ecommerce-net
    depends_on:
      kafka:
        condition: service_healthy

  payments:
    build: ../services/payments
    ports:
      - "8003:8000"
    volumes:
      - ../services/payments:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - ecommerce-net
    depends_on:
      kafka:
        condition: service_healthy

  kafka:
    container_name: kafka
    image: apache/kafka:4.0.2
    ports:
      - "9092:9092"
    networks:
      - ecommerce-net
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
    healthcheck:
      test:
        [
          "CMD",
          "/opt/kafka/bin/kafka-broker-api-versions.sh",
          "--bootstrap-server",
          "localhost:9092",
        ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    networks:
      - ecommerce-net
    environment:
      - KAFKA_CLUSTERS_0_NAME=ecommerce-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy

  otel-collector:
      container_name: otel-collector
      image: otel/opentelemetry-collector-contrib:0.151.0
      command: ["--config=/etc/collector-config.yaml"]
      volumes:
        - ./otel/otel-collector-config.yaml:/etc/collector-config.yaml  
      ports:
        - "4317:4317"
        - "4318:4318"
      networks:
        - ecommerce-net
      depends_on:
        - prometheus
        - tempo
        - loki

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./otel/prometheus.yml:/etc/prometheus/prometheus.yml  # ← otel/
      ports:
        - "9090:9090"
      networks:
        - ecommerce-net

  tempo:
      image: grafana/tempo:latest
      container_name: tempo
      command: ["-config.file=/etc/tempo.yaml"]
      volumes:
        - ./otel/tempo.yaml:/etc/tempo.yaml  # ← otel/
      ports:
        - "3200:3200"
        - "4319:4317"
      networks:
        - ecommerce-net

  loki:
      image: grafana/loki:latest
      container_name: loki
      ports:
        - "3100:3100"
      networks:
        - ecommerce-net

  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"
      environment:
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      volumes:
        - ./otel/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
        - ./otel/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
        - ./otel/ecommerce.json:/var/lib/grafana/dashboards/ecommerce.json
      networks:
        - ecommerce-net
      depends_on:
        - prometheus
        - tempo
        - loki

networks:
  ecommerce-net:
    driver: bridge

