apiVersion: v1
kind: Secret
metadata:
  name: kafka-cluster-id
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
type: Opaque
stringData:
  cluster-id: {{ .Values.clusterId | quote }}
