apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-realm
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  ecommerce-realm.json: |
{{ include "keycloak.realmJson" . | indent 4 }}
